#!/usr/bin/env python
"""
author : Philippe Vo
date : 2019-September-21 15:06:47
"""
# * Imports
# 3rd party Imports
import argparse
import os
import sys
from datetime import date, datetime
import subprocess

# * Code
# CLI Parser
parser = argparse.ArgumentParser()
group = parser.add_mutually_exclusive_group()
group.add_argument("-r", "--room", action="store_true")
group.add_argument("-i", "--inclass", action="store_true")
group.add_argument("-t", "--tutorial", action="store_true")
args = parser.parse_args()

# * Init all the setup variables
# Note Type
if args.room:
    noteType = "Room"
elif args.inclass:
    noteType = "InClass"
elif args.tutorial:
    noteType = "Tutorial"
else :
    noteType = "Default"

# Date
today = date.today()
dateStr = today.strftime("%b-%d-%Y")

now = datetime.now()
dateTimeStr = now.strftime("%b-%d-%Y %H:%M:%S")

# Filename
filename = dateStr.upper() + "-" + noteType + ".md"

# Section headings
headerOne = "# " + noteType + " Notes" + "\n"
classStr = "class : \n"
slideStr = "slide : \n"
noteSection = "## Notes \n"
questionSection = "## Questions \n"
importantSection = "## Important \n"
newLine = "\n"

# File Creation
if os.path.exists(filename) :
    print("File Already exists. Exiting...")
    sys.exit()

noteFile = open(filename, "w+")

# Writing to File
noteFile.write(headerOne)
noteFile.write(dateTimeStr)
noteFile.write(newLine)
noteFile.write(newLine)
noteFile.write(classStr)
noteFile.write(slideStr)
noteFile.write(newLine)
noteFile.write(noteSection)
noteFile.write(newLine)
noteFile.write(newLine)
noteFile.write(questionSection)
noteFile.write(newLine)
noteFile.write(newLine)
noteFile.write(importantSection)

# running vscode
subprocess.run(["code", "."])